spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
  jpa:
    show-sql: true

server:
  port: 8089

mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  type-aliases-package: com.study.pojo




